name: cc65-docker

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '0 7 * * 1'  # every monday at 7:00 https://crontab.guru/#0_7_*_*_1

jobs:
  image:
    name: build and deploy
    runs-on: ubuntu-20.04
    steps:
      - name: "ğŸ“¥ Checkout Code"
        uses: actions/checkout@v2.2.0
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "ğŸ› ï¸ Build"
        run: docker build -t bensuperpc/cc65:$(date +%Y-%m-%d) -t bensuperpc/cc65:latest .
      - name: "ğŸ“¤ Upload to hub.docker.com"
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            docker image push bensuperpc/cc65 --all-tags
